# Generated by Django 6.0.3 on 2026-05-18 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0002_alter_quizattempt_result_category_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answerchoice",
            options={"ordering": ["id"]},
        ),
    ]
