# Generated by Django 6.0.2 on 2026-05-20 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0003_answerchoice_ordering"),
    ]

    operations = [
        migrations.AddField(
            model_name="answerchoice",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="answer_choices",
                to="quizzes.resultcategory",
            ),
        ),
        migrations.AlterField(
            model_name="answerchoice",
            name="side",
            field=models.CharField(
                blank=True,
                choices=[("left", "Left"), ("right", "Right")],
                default="",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="dimension",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="quizzes.dimension",
            ),
        ),
    ]
