# Generated by Django 6.0.2 on 2026-05-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0005_quiz_result_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="answerchoice",
            name="points",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
